window.translations = window.translations || {};
window.translations.ar = {
  nav: { home: 'الرئيسية', profile: 'الملف الشخصي', skills: 'المهارات', experience: 'الخبرة', projects: 'المشاريع', education: 'التعليم', contact: 'اتصل' },
  hero: { greeting: 'مرحبًا، أنا', name: 'Rayner Alejandro Soto Martínez', title: 'مطور Java Backend', location: 'هافانا، كوبا | متاح للعمل عن بعد', download: 'تحميل السيرة الذاتية', contact: 'تواصل معي' },
  profile: { eyebrow: 'عني', title: 'الملف المهني', text: 'مهندس حاسوب ومطور Backend، متخصص في تطوير Java Backend مع أكثر من 3 سنوات من الخبرة في بناء تطبيقات مؤسسية قابلة للتوسع. خبير في النظام البيئي لـ Spring Framework (Spring Boot، Spring Cloud، Spring Security، Spring Data JPA) لبناء خدمات متناهية الصغر و RESTful API قوية. لديه خبرة مثبتة في تحويل الأنظمة الأحادية إلى بنى موزعة باستخدام أنماط Hexagonal Architecture ومبادئ Domain-Driven Design (DDD). ماهر في تصميم وتحسين قواعد البيانات العلائقية (PostgreSQL، MySQL) مع قدرات قوية في تكامل البيانات الجغرافية المكانية (PostGIS) وأتمتة عمليات ETL. ملتزم بتقديم حلول عالية الجودة من خلال ممارسات DevOps (Docker، Flyway، GitHub Actions)، والاختبارات الصارمة (JUnit، Mockito)، وتحليل الكود (SonarQube). سجل حافل بالعمل مع منهجيات Agile (Scrum) والمساهمة في فرق تطوير موزعة.' },
  skills: { eyebrow: 'خبراتي', title: 'المهارات التقنية', categories: [
    { name: 'لغات البرمجة', items: ['Java (JDK 8, 11, 14, 17, 21, 22, 25, GraalVM)', 'Scala', 'Python', 'C', 'JavaScript'] },
    { name: 'الأطر العمل وبيئة Spring', items: ['Spring Boot', 'Spring AOP', 'Spring Cloud', 'Spring Security (JWT)', 'Spring Data JPA', 'Spring Data JDBC', 'Spring Batch', 'Spring MVC', 'Hibernate', 'JPA'] },
    { name: 'قواعد البيانات', items: ['PostgreSQL', 'PostGIS', 'MySQL', 'SQL Server', 'SQLite', 'H2', 'Oracle DB', 'JDBC', 'Flyway'] },
    { name: 'هندسة البرمجيات', items: ['Microservices', 'Hexagonal Architecture', 'Domain-Driven Design', 'MVC', 'UML 2.0'] },
    { name: 'DevOps والأدوات', items: ['Docker', 'Maven', 'Gradle', 'Git', 'GitHub Actions', 'Apache Tomcat', 'CI/CD'] },
    { name: 'الاختبار والجودة', items: ['JUnit', 'Mockito', 'SonarQube', 'Code Review', 'Clean Code', 'SOLID', 'Design Patterns'] },
    { name: 'الواجهة الأمامية', items: ['HTML5', 'CSS3', 'JavaScript', 'Thymeleaf', 'PrimeFaces', 'Jakarta EE', 'React'] },
    { name: 'معالجة البيانات', items: ['Apache POI', 'ETL', 'GIS'] }
  ] },
  experience: { eyebrow: 'المسيرة المهنية', title: 'الخبرة المهنية', jobs: [
    { title: 'محلل ومطور Java Full-Stack', company: 'Gecytes', period: 'نوفمبر 2024 - الحاضر', location: 'عن بعد، المكسيك', details: ['تصميم خدمات backend ضمن Microservices و Hexagonal Architecture.', 'تنفيذ RESTful API مع Spring Boot و Spring Cloud.', 'إدارة PostgreSQL (PostGIS) مع البيانات الجغرافية المكانية.', 'ضمان الجودة مع JUnit و SonarQube و Docker.', 'التعاون agile مع Git/GitHub.'], stack: ['Java 17/21/25', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'Hibernate', 'React', 'PostgreSQL (PostGIS)', 'Docker', 'Maven'] },
    { title: 'مطور Java Backend', company: 'Gestini', period: 'مايو 2025 - يونيو 2025', location: 'عن بعد، الأرجنتين', details: ['تصميم وتنفيذ ميزات backend قابلة للتوسع.', 'تنفيذ اختبارات الوحدة لضمان المتانة والاستقرار.'], stack: ['Java 17/21', 'Spring Boot', 'Spring Data', 'Spring Security', 'Hibernate', 'MySQL', 'Docker', 'Maven'] },
    { title: 'مطور Scala Backend', company: 'Arkon Data', period: 'مارس 2025 - مايو 2025', location: 'عن بعد، المكسيك', details: ['تعمق في Scala والبرمجة الوظيفية لتطوير backend.', 'تحليل البنى القابلة للتوسع والخدمات المتناهية الصغر.', 'المشاركة في مراجعة الكود وتحسين الخدمات.'], stack: ['Scala', 'Functional Programming', 'Microservices', 'Git', 'GitHub'] },
    { title: 'محلل ومطور Java Back-End', company: 'CUJAE', period: 'يناير 2024 - نوفمبر 2024', location: 'هافانا، كوبا', details: ['القيادة التقنية في التحول متعدد المنصات من desktop إلى web.', 'إنشاء RESTful API وأتمتة ETL مع Apache POI.', 'تحسين البيانات الجغرافية المكانية باستخدام PostGIS.'], stack: ['Java 17', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'PostgreSQL (PostGIS)', 'Apache POI', 'Maven'] },
    { title: 'مطور Java وأخصائي قواعد بيانات', company: 'CUJAE', period: 'سبتمبر 2022 - يوليو 2023', location: 'هافانا، كوبا', details: ['تطوير أدوات أتمتة Java لنقل البيانات.', 'إعادة تصميم وتحسين قواعد البيانات العلائقية.', 'تنفيذ triggers و functions لسلامة المرجعية.'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'SQL', 'Git', 'GitHub'] },
    { title: 'محلل ومطور برمجيات Java', company: 'CUJAE', period: 'يناير 2022 - سبتمبر 2022', location: 'هافانا، كوبا', details: ['إنشاء حلول إدارة المعلومات الجغرافية المكانية.', 'أتمتة تحويل Excel إلى قاعدة بيانات علائقية.', 'تطوير واجهات Java Swing لتحليل البيانات.'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'Apache POI', 'GIS', 'Git'] }
  ] },
  projects: { eyebrow: 'أعمال مميزة', title: 'المشاريع المميزة', list: [
    { title: 'نظام مراقبة وتحليل بيانات المستشعرات الذكية', subtitle: 'رسالة البكالوريوس - CUJAE', period: '2024 - 2025', description: 'نظام backend لمراقبة وإدارة وتحليل البيانات من المستشعرات الذكية المتصلة بالجسم. يدمج الخدمات المتناهية الصغر والذكاء الاصطناعي وإنترنت الأشياء لتشخيص الأمراض من خلال تحليل أنماط المشي.', highlights: ['هندسة Microservices مع Spring Boot و Spring Cloud (Gateway, Eureka)', 'الشبكات العصبية مع Neuroph لتصنيف أنماط المشي', 'إنترنت الأشياء مع مستشعرات ESP32 و Bluetooth', 'تطبيق Android أصلي مع مزامنة SQLite و PostgreSQL', 'الأمان مع Spring Security (JWT)'], stack: ['Java 17', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'Spring Data JPA', 'Hibernate', 'PostgreSQL', 'SQLite', 'Android', 'Neuroph', 'IoT', 'Maven'] },
    { title: 'النظام الجغرافي لإدارة تربية النحل', subtitle: 'Gecytes', period: 'نوفمبر 2024 - الحاضر', description: 'نظام جغرافي لإدارة تربية النحل في المكسيك مع تمثيل مكاني للخلايا والمناحل والمسارات.', highlights: ['RESTful API قوي مع تكامل البيانات الجغرافية المكانية', 'تحسين الأداء والمصادقة/التفويض', 'PostgreSQL مع إضافة GIS', 'إدارة إصدارات قاعدة البيانات مع Flyway ونشر Docker', 'توثيق معماري شامل'], stack: ['Java 17/21/25', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'Spring Data JPA', 'Hibernate', 'PostgreSQL (PostGIS)', 'Flyway', 'Docker', 'Maven', 'JUnit', 'SonarQube'] },
    { title: 'نظام Backend لإدارة الموظفين مع التحديد الجغرافي', subtitle: 'CUJAE - ويب', period: 'يناير 2024 - نوفمبر 2024', description: 'نظام ويب لإدارة عمليات شركة نقل سياحي مع التكامل الجغرافي المكاني.', highlights: ['Backend مع Spring Framework و Spring Data JDBC', 'واجهة ويب مع JSF و PrimeFaces', 'وحدات إدارة السائقين والحافلات والطلبات', 'مخططات معمارية وتوثيق تقني'], stack: ['Java', 'Spring Boot', 'Spring Data JDBC', 'JSF', 'PrimeFaces', 'PostgreSQL', 'Maven', 'Swagger', 'UML'] },
    { title: 'نظام التحكم في السائقين والحافلات', subtitle: 'CUJAE - النقل السياحي', period: 'سبتمبر 2023 - فبراير 2024', description: 'نظام إدارة لشركة نقل سياحي يدمج backend وواجهة ويب أمامية.', highlights: ['Backend مع Spring Framework و Spring Data JDBC و Spring MVC', 'واجهة ويب مع JSF و PrimeFaces', 'التحقق من تكامل البيانات وإدارتها'], stack: ['Java', 'Spring Boot', 'Spring Data JDBC', 'Spring MVC', 'Spring Security', 'JSF', 'PrimeFaces', 'PostgreSQL', 'Maven'] },
    { title: 'قاعدة بيانات جرد الحاسوب', subtitle: 'CUJAE - كلية هندسة الحاسوب', period: 'سبتمبر 2022 - يوليو 2023', description: 'نقل نظام جرد قائم على Excel إلى قاعدة بيانات علائقية PostgreSQL.', highlights: ['نقل وتحويل البيانات من Excel إلى PostgreSQL', 'نموذج إدارة جرد منظم وفعال', 'استعلامات SQL محسنة لاستخراج المعلومات'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'Apache POI', 'UML', 'Git'] },
    { title: 'نظام إدارة الموظفين مع التحديد الجغرافي', subtitle: 'CUJAE - سطح المكتب', period: 'يناير 2022 - يوليو 2022', description: 'نظام سطح مكتب لمركزة بيانات Excel في قاعدة بيانات علائقية مع معالجة جغرافية مكانية.', highlights: ['استيراد وتخزين من Excel إلى PostgreSQL', 'توليد مصفوفة اتصال ثنائية الأبعاد', 'أتمتة مع تكامل GIS'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'Apache POI', 'GIS', 'UML', 'Git'] },
    { title: 'نظام التحكم في السائقين والحافلات', subtitle: 'CUJAE - سطح المكتب', period: 'يناير 2021 - نوفمبر 2021', description: 'نظام سطح مكتب لإدارة السائقين والحافلات في شركة نقل سياحي.', highlights: ['منطق أعمال Java كائني التوجه', 'واجهة رسومية مع Java Swing', 'إدارة بيانات شاملة وتوثيق تقني'], stack: ['Java', 'PostgreSQL', 'Java Swing', 'OOP', 'Eclipse IDE'] }
  ] },
  education: { eyebrow: 'التعليم', title: 'التعليم', degree: { title: 'هندسة الحاسوب', institution: 'جامعة هافانا التكنولوجية "José Antonio Echeverría" (CUJAE)', period: 'سبتمبر 2018 - الحاضر', detail: 'التخرج المتوقع: 2026 (بانتظار مناقشة الأطروحة - تم استكمال جميع الساعات المعتمدة)', focus: 'تدريب شامل في هندسة البرمجيات والخوارزميات المتقدمة وهندسة النظم الموزعة.' }, complementary: { title: 'التعليم التكميلي', courses: [ { name: 'منحة KetherLabs - Datacamp', period: 'يناير 2026 - الحاضر', detail: 'معالجة البيانات الضخمة والنمذجة الإحصائية والتحليلات التنبؤية.' }, { name: 'أخصائي Java Backend - Oracle ONE', period: 'يناير 2024 - يوليو 2024', detail: 'النظام البيئي لـ Java، Spring Framework، Spring Boot، Spring Data JPA/Hibernate، Spring Security، MySQL، SOLID، Clean Code، Design Patterns.' }, { name: 'LinkedIn Learning', period: '', detail: 'Java (مبتدئ إلى متقدم)، البرمجة الوظيفية مع Scala، Spring Framework، Spring Data JPA، JDBC، REST APIs، HTML5، CSS3، JavaScript، Git/GitHub، Scrum.' } ] }, languages: { title: 'اللغات', items: [ { name: 'الإسبانية', level: 'اللغة الأم' }, { name: 'الإنجليزية', level: 'متوسط (A2-B1) | القراءة التقنية: متقدم' } ] } },
  contact: { eyebrow: 'تواصل معي', title: 'اتصل', subtitle: 'أنا منفتح لفرص العمل والتعاونات.', email: 'raynersoto01@gmail.com', phone: '+1 (863) 766-8212', whatsapp: '+1 (863) 397-6979', location: 'هافانا، كوبا', linkedin: 'linkedin.com/in/rayner-alejandro', github: 'github.com/RaynerSoto' },
  footer: { copyright: '\u00a9 2026 Rayner Alejandro Soto Mart\u00ednez. جميع الحقوق محفوظة.', built: 'بني باستخدام' }
};
