window.translations = window.translations || {};
window.translations.id = {
  nav: { home: 'Beranda', profile: 'Profil', skills: 'Keahlian', experience: 'Pengalaman', projects: 'Proyek', education: 'Pendidikan', contact: 'Kontak' },
  hero: { greeting: 'Halo, saya', name: 'Rayner Alejandro Soto Martínez', title: 'Pengembang Java Backend', location: 'Havana, Kuba | Tersedia untuk kerja jarak jauh', download: 'Unduh CV', contact: 'Hubungi saya' },
  profile: { eyebrow: 'Tentang saya', title: 'Profil Profesional', text: 'Insinyur Komputer dan Pengembang Backend, yang berspesialisasi dalam Pengembangan Java Backend dengan lebih dari 3 tahun pengalaman membangun aplikasi perusahaan berskala besar. Ahli dalam ekosistem Spring Framework (Spring Boot, Spring Cloud, Spring Security, Spring Data JPA) untuk membangun mikroservis dan RESTful API yang tangguh. Berpengalaman dalam mentransformasi sistem monolitik menjadi arsitektur terdistribusi menggunakan pola Arsitektur Heksagonal dan prinsip Domain-Driven Design (DDD). Terampil dalam perancangan dan optimalisasi basis data relasional (PostgreSQL, MySQL) dengan kemampuan kuat dalam integrasi data geospasial (PostGIS) dan otomatisasi proses ETL. Berkomitmen memberikan solusi berkualitas melalui praktik DevOps (Docker, Flyway, GitHub Actions), pengujian ketat (JUnit, Mockito), dan analisis kode (SonarQube). Memiliki rekam jejak terbukti bekerja dengan metodologi Agile (Scrum) dan berkontribusi pada tim pengembangan terdistribusi.' },
  skills: { eyebrow: 'Keahlian saya', title: 'Keahlian Teknis', categories: [
    { name: 'Bahasa Pemrograman', items: ['Java (JDK 8, 11, 14, 17, 21, 22, 25, GraalVM)', 'Scala', 'Python', 'C', 'JavaScript'] },
    { name: 'Framework & Ekosistem Spring', items: ['Spring Boot', 'Spring AOP', 'Spring Cloud', 'Spring Security (JWT)', 'Spring Data JPA', 'Spring Data JDBC', 'Spring Batch', 'Spring MVC', 'Hibernate', 'JPA'] },
    { name: 'Basis Data', items: ['PostgreSQL', 'PostGIS', 'MySQL', 'SQL Server', 'SQLite', 'H2', 'Oracle DB', 'JDBC', 'Flyway'] },
    { name: 'Arsitektur Perangkat Lunak', items: ['Microservices', 'Hexagonal Architecture', 'Domain-Driven Design', 'MVC', 'UML 2.0'] },
    { name: 'DevOps & Alat', items: ['Docker', 'Maven', 'Gradle', 'Git', 'GitHub Actions', 'Apache Tomcat', 'CI/CD'] },
    { name: 'Pengujian & Kualitas', items: ['JUnit', 'Mockito', 'SonarQube', 'Code Review', 'Clean Code', 'SOLID', 'Design Patterns'] },
    { name: 'Frontend', items: ['HTML5', 'CSS3', 'JavaScript', 'Thymeleaf', 'PrimeFaces', 'Jakarta EE', 'React'] },
    { name: 'Pemrosesan Data', items: ['Apache POI', 'ETL', 'GIS'] }
  ] },
  experience: { eyebrow: 'Karier', title: 'Pengalaman Profesional', jobs: [
    { title: 'Analis dan Pengembang Java Full-Stack', company: 'Gecytes', period: 'Nov 2024 - Sekarang', location: 'Remote, Meksiko', details: ['Perancangan layanan backend dengan Microservices dan Arsitektur Heksagonal.', 'Implementasi RESTful API dengan Spring Boot dan Spring Cloud.', 'Manajemen PostgreSQL (PostGIS) dengan data geospasial.', 'Jaminan kualitas dengan JUnit, SonarQube dan Docker.', 'Kolaborasi tangkas dengan Git/GitHub.'], stack: ['Java 17/21/25', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'Hibernate', 'React', 'PostgreSQL (PostGIS)', 'Docker', 'Maven'] },
    { title: 'Pengembang Java Backend', company: 'Gestini', period: 'Mei 2025 - Jun 2025', location: 'Remote, Argentina', details: ['Perancangan dan implementasi fitur backend yang skalabel.', 'Implementasi pengujian unit untuk memastikan ketahanan dan stabilitas.'], stack: ['Java 17/21', 'Spring Boot', 'Spring Data', 'Spring Security', 'Hibernate', 'MySQL', 'Docker', 'Maven'] },
    { title: 'Pengembang Scala Backend', company: 'Arkon Data', period: 'Mar 2025 - Mei 2025', location: 'Remote, Meksiko', details: ['Pendalaman Scala dan pemrograman fungsional untuk pengembangan backend.', 'Analisis arsitektur skalabel dan mikroservis.', 'Partisipasi dalam Code Review dan optimalisasi layanan.'], stack: ['Scala', 'Functional Programming', 'Microservices', 'Git', 'GitHub'] },
    { title: 'Analis dan Pengembang Java Back-End', company: 'CUJAE', period: 'Jan 2024 - Nov 2024', location: 'Havana, Kuba', details: ['Kepemimpinan teknis dalam migrasi multiplatform dari desktop ke web.', 'Pembuatan RESTful API dan otomatisasi ETL dengan Apache POI.', 'Optimalisasi data geospasial dengan PostGIS.'], stack: ['Java 17', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'PostgreSQL (PostGIS)', 'Apache POI', 'Maven'] },
    { title: 'Pengembang Java & Spesialis Database', company: 'CUJAE', period: 'Sep 2022 - Jul 2023', location: 'Havana, Kuba', details: ['Pengembangan alat otomatisasi Java untuk migrasi data.', 'Perancangan ulang dan optimalisasi basis data relasional.', 'Implementasi trigger dan fungsi untuk integritas referensial.'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'SQL', 'Git', 'GitHub'] },
    { title: 'Analis dan Pengembang Perangkat Lunak Java', company: 'CUJAE', period: 'Jan 2022 - Sep 2022', location: 'Havana, Kuba', details: ['Pembuatan solusi manajemen informasi geospasial.', 'Otomatisasi konversi Excel ke basis data relasional.', 'Pengembangan antarmuka Java Swing untuk analisis data.'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'Apache POI', 'GIS', 'Git'] }
  ] },
  projects: { eyebrow: 'Karya unggulan', title: 'Proyek Unggulan', list: [
    { title: 'Sistem Pemantauan & Analisis Data Sensor Cerdas', subtitle: 'Skripsi - CUJAE', period: '2024 - 2025', description: 'Sistem backend untuk memantau, mengelola, dan menganalisis data dari sensor cerdas yang terhubung ke tubuh. Mengintegrasikan mikroservis, kecerdasan buatan, dan IoT untuk diagnosis patologi melalui analisis pola gaya berjalan.', highlights: ['Arsitektur Microservices dengan Spring Boot dan Spring Cloud (Gateway, Eureka)', 'Jaringan Saraf dengan Neuroph untuk klasifikasi pola gaya berjalan', 'IoT dengan sensor ESP32 dan Bluetooth', 'Aplikasi Android native dengan sinkronisasi SQLite dan PostgreSQL', 'Keamanan dengan Spring Security (JWT)'], stack: ['Java 17', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'Spring Data JPA', 'Hibernate', 'PostgreSQL', 'SQLite', 'Android', 'Neuroph', 'IoT', 'Maven'] },
    { title: 'Sistem Geografis untuk Manajemen Peternakan Lebah', subtitle: 'Gecytes', period: 'Nov 2024 - Sekarang', description: 'Sistem geografis untuk manajemen peternakan lebah di Meksiko dengan representasi geospasial sarang, lokasi lebah, dan rute.', highlights: ['RESTful API yang tangguh dengan integrasi data geospasial', 'Optimalisasi kinerja dan otentikasi/otorisasi', 'PostgreSQL dengan ekstensi GIS', 'Versioning basis data dengan Flyway dan deployment Docker', 'Dokumentasi arsitektur yang komprehensif'], stack: ['Java 17/21/25', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'Spring Data JPA', 'Hibernate', 'PostgreSQL (PostGIS)', 'Flyway', 'Docker', 'Maven', 'JUnit', 'SonarQube'] },
    { title: 'Sistem Backend Manajemen Personalia dengan Georeferensi', subtitle: 'CUJAE - Web', period: 'Jan 2024 - Nov 2024', description: 'Sistem web untuk mengelola operasi perusahaan transportasi wisata dengan integrasi geospasial.', highlights: ['Backend dengan Spring Framework dan Spring Data JDBC', 'Antarmuka web dengan JSF dan PrimeFaces', 'Modul manajemen pengemudi, bus, dan permintaan', 'Diagram arsitektur dan dokumentasi teknis'], stack: ['Java', 'Spring Boot', 'Spring Data JDBC', 'JSF', 'PrimeFaces', 'PostgreSQL', 'Maven', 'Swagger', 'UML'] },
    { title: 'Sistem Kontrol Pengemudi dan Bus', subtitle: 'CUJAE - Transportasi Wisata', period: 'Sep 2023 - Feb 2024', description: 'Sistem manajemen untuk perusahaan transportasi wisata yang mengintegrasikan backend dan frontend web.', highlights: ['Backend dengan Spring Framework, Spring Data JDBC dan Spring MVC', 'Antarmuka web dengan JSF dan PrimeFaces', 'Validasi integritas data dan manajemen'], stack: ['Java', 'Spring Boot', 'Spring Data JDBC', 'Spring MVC', 'Spring Security', 'JSF', 'PrimeFaces', 'PostgreSQL', 'Maven'] },
    { title: 'Database Inventaris Komputer', subtitle: 'CUJAE - Fakultas Teknik Komputer', period: 'Sep 2022 - Jul 2023', description: 'Migrasi sistem inventaris berbasis Excel ke basis data relasional PostgreSQL.', highlights: ['Migrasi dan transformasi data dari Excel ke PostgreSQL', 'Model manajemen inventaris yang terstruktur dan efisien', 'Kueri SQL yang dioptimalkan untuk ekstraksi informasi'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'Apache POI', 'UML', 'Git'] },
    { title: 'Sistem Manajemen Personalia dengan Georeferensi', subtitle: 'CUJAE - Desktop', period: 'Jan 2022 - Jul 2022', description: 'Sistem desktop untuk memusatkan data Excel ke basis data relasional dengan pemrosesan geospasial.', highlights: ['Impor dan penyimpanan dari Excel ke PostgreSQL', 'Pembuatan matriks koneksi dua dimensi', 'Otomatisasi dengan integrasi GIS'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'Apache POI', 'GIS', 'UML', 'Git'] },
    { title: 'Sistem Kontrol Pengemudi dan Bus', subtitle: 'CUJAE - Desktop', period: 'Jan 2021 - Nov 2021', description: 'Sistem desktop untuk manajemen pengemudi dan bus di perusahaan transportasi wisata.', highlights: ['Logika bisnis Java berorientasi objek', 'Antarmuka grafis dengan Java Swing', 'Manajemen data lengkap dan dokumentasi teknis'], stack: ['Java', 'PostgreSQL', 'Java Swing', 'OOP', 'Eclipse IDE'] }
  ] },
  education: { eyebrow: 'Pendidikan', title: 'Pendidikan', degree: { title: 'Teknik Komputer', institution: 'Universitas Teknologi Havana "José Antonio Echeverría" (CUJAE)', period: 'Sep 2018 - Sekarang', detail: 'Perkiraan kelulusan: 2026 (Menunggu sidang skripsi - Semua kredit selesai)', focus: 'Pelatihan komprehensif dalam rekayasa perangkat lunak, algoritma lanjutan, dan arsitektur sistem terdistribusi.' }, complementary: { title: 'Pendidikan Tambahan', courses: [ { name: 'Beasiswa KetherLabs - Datacamp', period: 'Jan 2026 - Sekarang', detail: 'Pemrosesan data masif, pemodelan statistik, dan analitik prediktif.' }, { name: 'Spesialis Java Backend - Oracle ONE', period: 'Jan 2024 - Jul 2024', detail: 'Ekosistem Java, Spring Framework, Spring Boot, Spring Data JPA/Hibernate, Spring Security, MySQL, SOLID, Clean Code, Design Patterns.' }, { name: 'LinkedIn Learning', period: '', detail: 'Java (Pemula hingga Mahir), Pemrograman fungsional dengan Scala, Spring Framework, Spring Data JPA, JDBC, REST APIs, HTML5, CSS3, JavaScript, Git/GitHub, Scrum.' } ] }, languages: { title: 'Bahasa', items: [ { name: 'Spanyol', level: 'Bahasa ibu' }, { name: 'Inggris', level: 'Menengah (A2-B1) | Membaca teknis: Mahir' } ] } },
  contact: { eyebrow: 'Mari terhubung', title: 'Kontak', subtitle: 'Saya terbuka untuk peluang kerja dan kolaborasi.', email: 'raynersoto01@gmail.com', phone: '+1 (863) 766-8212', whatsapp: '+1 (863) 397-6979', location: 'Havana, Kuba', linkedin: 'linkedin.com/in/rayner-alejandro', github: 'github.com/RaynerSoto' },
  footer: { copyright: '\u00a9 2026 Rayner Alejandro Soto Mart\u00ednez. Hak cipta dilindungi.', built: 'Dibangun dengan' }
};
