window.translations = window.translations || {};
window.translations.th = {
  nav: { home: 'หน้าแรก', profile: 'โปรไฟล์', skills: 'ทักษะ', experience: 'ประสบการณ์', projects: 'โครงการ', education: 'การศึกษา', contact: 'ติดต่อ' },
  hero: { greeting: 'สวัสดี, ผมชื่อ', name: 'Rayner Alejandro Soto Martínez', title: 'นักพัฒนา Java Backend', location: 'ฮาวานา, คิวบา | พร้อมทำงานระยะไกล', download: 'ดาวน์โหลด CV', contact: 'ติดต่อฉัน' },
  profile: { eyebrow: 'เกี่ยวกับฉัน', title: 'โปรไฟล์มืออาชีพ', text: 'วิศวกรคอมพิวเตอร์และนักพัฒนา Backend ที่เชี่ยวชาญด้านการพัฒนา Java Backend มากกว่า 3 ปีในการสร้างแอปพลิเคชันระดับวิสาหกิจที่ประสิทธิภาพและปรับขนาดได้ เชี่ยวชาญในระบบนิเวศของ Spring Framework (Spring Boot, Spring Cloud, Spring Security, Spring Data JPA) สำหรับการสร้าง microservices และ RESTful API ที่แข็งแกร่ง มีประสบการณ์ที่พิสูจน์แล้วในการเปลี่ยนระบบเดี่ยวไปเป็นสถาปัตยกรรมแบบกระจายโดยใช้รูปแบบ Hexagonal Architecture และหลักการ Domain-Driven Design (DDD) ชำนาญในการออกแบบและเพิ่มประสิทธิภาพฐานข้อมูลเชิงสัมพันธ์ (PostgreSQL, MySQL) ด้วยความสามารถที่แข็งแกร่งในการบูรณาการข้อมูลภูมิศาสตร์ศาสตร์ (PostGIS) และกระบวนการอัตโนมัติ ETL มุ่งมั่นในการส่งมอบโซลูชันที่มีคุณภาพผ่านแนวปฏิบัติ DevOps (Docker, Flyway, GitHub Actions), การทดสอบที่เข้มงวด (JUnit, Mockito), และการวิเคราะห์โค้ด (SonarQube) มีผลงานที่พิสูจน์แล้วในการทำงานกับระเบียบวิธี Agile (Scrum) และการมีส่วนร่วมกับทีมพัฒนาแบบกระจาย' },
  skills: { eyebrow: 'ความเชี่ยวชาญของฉัน', title: 'ทักษะทางเทคนิค', categories: [
    { name: 'ภาษาโปรแกรม', items: ['Java (JDK 8, 11, 14, 17, 21, 22, 25, GraalVM)', 'Scala', 'Python', 'C', 'JavaScript'] },
    { name: 'เฟรมเวิร์กและระบบนิเวศ Spring', items: ['Spring Boot', 'Spring AOP', 'Spring Cloud', 'Spring Security (JWT)', 'Spring Data JPA', 'Spring Data JDBC', 'Spring Batch', 'Spring MVC', 'Hibernate', 'JPA'] },
    { name: 'ฐานข้อมูล', items: ['PostgreSQL', 'PostGIS', 'MySQL', 'SQL Server', 'SQLite', 'H2', 'Oracle DB', 'JDBC', 'Flyway'] },
    { name: 'สถาปัตยกรรมซอฟต์แวร์', items: ['Microservices', 'Hexagonal Architecture', 'Domain-Driven Design', 'MVC', 'UML 2.0'] },
    { name: 'DevOps และเครื่องมือ', items: ['Docker', 'Maven', 'Gradle', 'Git', 'GitHub Actions', 'Apache Tomcat', 'CI/CD'] },
    { name: 'การทดสอบและคุณภาพ', items: ['JUnit', 'Mockito', 'SonarQube', 'Code Review', 'Clean Code', 'SOLID', 'Design Patterns'] },
    { name: 'ฟรอนต์เอนด์', items: ['HTML5', 'CSS3', 'JavaScript', 'Thymeleaf', 'PrimeFaces', 'Jakarta EE', 'React'] },
    { name: 'การประมวลผลข้อมูล', items: ['Apache POI', 'ETL', 'GIS'] }
  ] },
  experience: { eyebrow: 'อาชีพ', title: 'ประสบการณ์ทางอาชีพ', jobs: [
    { title: 'นักวิเคราะห์และนักพัฒนา Java Full-Stack', company: 'Gecytes', period: 'พ.ย. 2567 - ปัจจุบัน', location: 'ระยะไกล, เม็กซิโก', details: ['ออกแบบบริการ backend ภายใต้ Microservices และ Hexagonal Architecture', 'ดำเนินการ RESTful API ด้วย Spring Boot และ Spring Cloud', 'จัดการ PostgreSQL (PostGIS) กับข้อมูลภูมิศาสตร์ศาสตร์', 'ประกันคุณภาพด้วย JUnit, SonarQube และ Docker', 'ทำงานร่วมกันแบบ Agile ด้วย Git/GitHub'], stack: ['Java 17/21/25', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'Hibernate', 'React', 'PostgreSQL (PostGIS)', 'Docker', 'Maven'] },
    { title: 'นักพัฒนา Java Backend', company: 'Gestini', period: 'พ.ค. 2568 - มิ.ย. 2568', location: 'ระยะไกล, อาร์เจนตินา', details: ['ออกแบบและดำเนินการฟีเจอร์ backend ที่ประสิทธิภาพและปรับขนาดได้', 'ดำเนินการทดสอบหน่วยเพื่อความแข็งแกร่งและความมั่นคง'], stack: ['Java 17/21', 'Spring Boot', 'Spring Data', 'Spring Security', 'Hibernate', 'MySQL', 'Docker', 'Maven'] },
    { title: 'นักพัฒนา Scala Backend', company: 'Arkon Data', period: 'มี.ค. 2568 - พ.ค. 2568', location: 'ระยะไกล, เม็กซิโก', details: ['เจาะลึกใน Scala และการเขียนโปรแกรมแบบฟังก์ชันสำหรับการพัฒนา backend', 'วิเคราะห์สถาปัตยกรรมที่ปรับขนาดได้และไมโครเซอร์วิส', 'เข้าร่วม Code Review และปรับปรุงบริการ'], stack: ['Scala', 'Functional Programming', 'Microservices', 'Git', 'GitHub'] },
    { title: 'นักวิเคราะห์และนักพัฒนา Java Back-End', company: 'CUJAE', period: 'ม.ค. 2567 - พ.ย. 2567', location: 'ฮาวานา, คิวบา', details: ['ความเป็นผู้นำด้านเทคนิคในการย้ายแพลตฟอร์มจาก desktop สู่ web', 'การสร้าง RESTful API และอัตโนมัติ ETL ด้วย Apache POI', 'เพิ่มประสิทธิภาพข้อมูลภูมิศาสตร์ด้วย PostGIS'], stack: ['Java 17', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'PostgreSQL (PostGIS)', 'Apache POI', 'Maven'] },
    { title: 'นักพัฒนา Java และผู้เชี่ยวชาญฐานข้อมูล', company: 'CUJAE', period: 'ก.ย. 2565 - ก.ค. 2566', location: 'ฮาวานา, คิวบา', details: ['พัฒนาเครื่องมืออัตโนมัติ Java สำหรับย้ายข้อมูล', 'ออกแบบใหม่และเพิ่มประสิทธิภาพฐานข้อมูลเชิงสัมพันธ์', 'ดำเนินการ trigger และ function สำหรับความถูกต้องของข้อมูลอ้างอิง'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'SQL', 'Git', 'GitHub'] },
    { title: 'นักวิเคราะห์และนักพัฒนาซอฟต์แวร์ Java', company: 'CUJAE', period: 'ม.ค. 2565 - ก.ย. 2565', location: 'ฮาวานา, คิวบา', details: ['สร้างโซลูชันการจัดการข้อมูลภูมิศาสตร์ศาสตร์', 'อัตโนมัติแปลง Excel เป็นฐานข้อมูลเชิงสัมพันธ์', 'พัฒนาอินเทอร์เฟส Java Swing สำหรับวิเคราะห์ข้อมูล'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'Apache POI', 'GIS', 'Git'] }
  ] },
  projects: { eyebrow: 'ผลงานเด่น', title: 'โครงการเด่น', list: [
    { title: 'ระบบติดตามและวิเคราะห์ข้อมูลเซ็นเซอร์อัจฉริยะ', subtitle: 'วิทยานิพนธ์ระดับปริญญาตรี - CUJAE', period: '2567 - 2568', description: 'ระบบ backend สำหรับการติดตาม จัดการ และวิเคราะห์ข้อมูลจากเซ็นเซอร์อัจฉริยะที่เชื่อมต่อกับร่างกาย ผสานรวม microservices, ปัญญาประดิษฐ์ และ IoT สำหรับการวินิจฉัยโรคผ่านการวิเคราะห์รูปแบบการเดิน', highlights: ['สถาปัตยกรรม Microservices ด้วย Spring Boot และ Spring Cloud (Gateway, Eureka)', 'เครือข่ายประสาทด้วย Neuroph สำหรับจำแนกรูปแบบการเดิน', 'IoT ด้วยเซ็นเซอร์ ESP32 และ Bluetooth', 'แอปพลิเคชัน Android ด้วยการซิงค์ SQLite และ PostgreSQL', 'ความปลอดภัยด้วย Spring Security (JWT)'], stack: ['Java 17', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'Spring Data JPA', 'Hibernate', 'PostgreSQL', 'SQLite', 'Android', 'Neuroph', 'IoT', 'Maven'] },
    { title: 'ระบบภูมิศาสตร์สำหรับการจัดการเลี้ยงผึ้ง', subtitle: 'Gecytes', period: 'พ.ย. 2567 - ปัจจุบัน', description: 'ระบบภูมิศาสตร์สำหรับการจัดการเลี้ยงผึ้งในเม็กซิโกพร้อมการแสดงผลเชิงพื้นที่ของรัง เลี้ยงผึ้ง และเส้นทาง', highlights: ['RESTful API ที่แข็งแกร่งพร้อมการบูรณาการข้อมูลภูมิศาสตร์', 'เพิ่มประสิทธิภาพและการตรวจสอบสิทธิ์/อนุญาต', 'PostgreSQL พร้อมส่วนขยาย GIS', 'จัดการเวอร์ชันฐานข้อมูลด้วย Flyway และการปรับใช้ Docker', 'เอกสารสถาปัตยกรรมที่ครอบคลุม'], stack: ['Java 17/21/25', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'Spring Data JPA', 'Hibernate', 'PostgreSQL (PostGIS)', 'Flyway', 'Docker', 'Maven', 'JUnit', 'SonarQube'] },
    { title: 'ระบบ Backend จัดการบุคลากรพร้อมอ้างอิงภูมิศาสตร์', subtitle: 'CUJAE - เว็บ', period: 'ม.ค. 2567 - พ.ย. 2567', description: 'ระบบเว็บสำหรับจัดการดำเนินงานของบริษัทขนส่งท่องเที่ยวพร้อมการบูรณาการภูมิศาสตร์', highlights: ['Backend ด้วย Spring Framework และ Spring Data JDBC', 'อินเทอร์เฟสเว็บด้วย JSF และ PrimeFaces', 'โมดูลจัดการพนักงานขับรถ รถบัส และคำขอ', 'ไดอะแกรมสถาปัตยกรรมและเอกสารทางเทคนิค'], stack: ['Java', 'Spring Boot', 'Spring Data JDBC', 'JSF', 'PrimeFaces', 'PostgreSQL', 'Maven', 'Swagger', 'UML'] },
    { title: 'ระบบควบคุมพนักงานขับรถและรถบัส', subtitle: 'CUJAE - ขนส่งท่องเที่ยว', period: 'ก.ย. 2566 - ก.พ. 2567', description: 'ระบบจัดการสำหรับบริษัทขนส่งท่องเที่ยวที่รวม backend และ frontend เว็บ', highlights: ['Backend ด้วย Spring Framework, Spring Data JDBC และ Spring MVC', 'อินเทอร์เฟสเว็บด้วย JSF และ PrimeFaces', 'ตรวจสอบความถูกต้องของข้อมูลและการจัดการ'], stack: ['Java', 'Spring Boot', 'Spring Data JDBC', 'Spring MVC', 'Spring Security', 'JSF', 'PrimeFaces', 'PostgreSQL', 'Maven'] },
    { title: 'ฐานข้อมูลคลังสินค้าคอมพิวเตอร์', subtitle: 'CUJAE - คณะวิศวกรรมศาสตร์คอมพิวเตอร์', period: 'ก.ย. 2565 - ก.ค. 2566', description: 'ย้ายระบบคลังสินค้าที่ใช้ Excel ไปยังฐานข้อมูลเชิงสัมพันธ์ PostgreSQL', highlights: ['ย้ายและแปลงข้อมูลจาก Excel ไปยัง PostgreSQL', 'โมเดลจัดการคลังสินค้าที่มีโครงสร้างและมีประสิทธิภาพ', 'คำสั่ง SQL ที่เพิ่มประสิทธิภาพสำหรับการสกัดข้อมูล'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'Apache POI', 'UML', 'Git'] },
    { title: 'ระบบจัดการบุคลากรพร้อมอ้างอิงภูมิศาสตร์', subtitle: 'CUJAE - เดสก์ท็อป', period: 'ม.ค. 2565 - ก.ค. 2565', description: 'ระบบเดสก์ท็อปสำหรับรวมข้อมูล Excel ไปยังฐานข้อมูลเชิงสัมพันธ์พร้อมการประมวลผลภูมิศาสตร์', highlights: ['นำเข้าและจัดเก็บจาก Excel ไปยัง PostgreSQL', 'สร้างเมทริกซ์การเชื่อมต่อสองมิติ', 'อัตโนมัติด้วยการบูรณาการ GIS'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'Apache POI', 'GIS', 'UML', 'Git'] },
    { title: 'ระบบควบคุมพนักงานขับรถและรถบัส', subtitle: 'CUJAE - เดสก์ท็อป', period: 'ม.ค. 2564 - พ.ย. 2564', description: 'ระบบเดสก์ท็อปสำหรับจัดการพนักงานขับรถและรถบัสในบริษัทขนส่งท่องเที่ยว', highlights: ['ตรรกะธุรกิจ Java เชิงวัตถุ', 'อินเทอร์เฟสกราฟิกด้วย Java Swing', 'จัดการข้อมูลครบถ้วนและเอกสารทางเทคนิค'], stack: ['Java', 'PostgreSQL', 'Java Swing', 'OOP', 'Eclipse IDE'] }
  ] },
  education: { eyebrow: 'การศึกษา', title: 'การศึกษา', degree: { title: 'วิศวกรรมคอมพิวเตอร์', institution: 'มหาวิทยาลัยเทคโนโลยีฮาวานา "José Antonio Echeverría" (CUJAE)', period: 'ก.ย. 2561 - ปัจจุบัน', detail: 'คาดว่าจะสำเร็จการศึกษา: 2569 (รอสอบวิทยานิพนธ์ - เรียนครบทุกหน่วยกิตแล้ว)', focus: 'การฝึกอบรมที่ครอบคลุมในด้านวิศวกรรมซอฟต์แวร์, อัลกอริทึมขั้นสูง และสถาปัตยกรรมระบบกระจาย' }, complementary: { title: 'การศึกษาเพิ่มเติม', courses: [ { name: 'ทุนการศึกษา KetherLabs - Datacamp', period: 'ม.ค. 2569 - ปัจจุบัน', detail: 'การประมวลผลข้อมูลขนาดใหญ่, การสร้างแบบจำลองทางสถิติ และการวิเคราะห์เชิงทำนาย' }, { name: 'ผู้เชี่ยวชาญ Java Backend - Oracle ONE', period: 'ม.ค. 2567 - ก.ค. 2567', detail: 'ระบบนิเวศ Java, Spring Framework, Spring Boot, Spring Data JPA/Hibernate, Spring Security, MySQL, SOLID, Clean Code, Design Patterns.' }, { name: 'LinkedIn Learning', period: '', detail: 'Java (ระดับเริ่มต้นถึงขั้นสูง), การเขียนโปรแกรมแบบฟังก์ชันด้วย Scala, Spring Framework, Spring Data JPA, JDBC, REST APIs, HTML5, CSS3, JavaScript, Git/GitHub, Scrum.' } ] }, languages: { title: 'ภาษา', items: [ { name: 'ภาษาสเปน', level: 'ภาษาแม่' }, { name: 'ภาษาอังกฤษ', level: 'ระดับกลาง (A2-B1) | การอ่านทางเทคนิค: ขั้นสูง' } ] } },
  contact: { eyebrow: 'ติดต่อฉัน', title: 'ติดต่อ', subtitle: 'ฉันพร้อมรับโอกาสทางอาชีพและการทำงานร่วมกัน', email: 'raynersoto01@gmail.com', phone: '+1 (863) 766-8212', whatsapp: '+1 (863) 397-6979', location: 'ฮาวานา, คิวบา', linkedin: 'linkedin.com/in/rayner-alejandro', github: 'github.com/RaynerSoto' },
  footer: { copyright: '\u00a9 2026 Rayner Alejandro Soto Mart\u00ednez. \u0e2a\u0e07\u0e27\u0e19\u0e25\u0e34\u0e02\u0e2a\u0e34\u0e17\u0e18\u0e34\u0e4c.', built: 'สร้างด้วย' }
};
