window.translations = window.translations || {};
window.translations.vi = {
  nav: { home: 'Trang chủ', profile: 'Hồ sơ', skills: 'Kỹ năng', experience: 'Kinh nghiệm', projects: 'Dự án', education: 'Học vấn', contact: 'Liên hệ' },
  hero: { greeting: 'Xin chào, tôi là', name: 'Rayner Alejandro Soto Martínez', title: 'Lập trình viên Java Backend', location: 'Havana, Cuba | Sẵn sàng làm việc từ xa', download: 'Tải CV xuống', contact: 'Liên hệ' },
  profile: { eyebrow: 'Về tôi', title: 'Hồ sơ Chuyên nghiệp', text: 'Kỹ sư Máy tính và Lập trình viên Backend, chuyên sâu về Phát triển Java Backend với hơn 3 năm kinh nghiệm xây dựng các ứng dụng doanh nghiệp có khả năng mở rộng. Thành thạo hệ sinh thái Spring Framework (Spring Boot, Spring Cloud, Spring Security, Spring Data JPA) để xây dựng các microservices và RESTful API mạnh mẽ. Có kinh nghiệm chuyển đổi các hệ thống nguyên khối thành kiến trúc phân tán sử dụng mô hình Kiến trúc Hexagonal và các nguyên lý Domain-Driven Design (DDD). Thành thạo trong thiết kế và tối ưu cơ sở dữ liệu quan hệ (PostgreSQL, MySQL) với khả năng mạnh về tích hợp dữ liệu không gian địa lý (PostGIS) và tự động hóa quy trình ETL. Cam kết mang đến các giải pháp chất lượng thông qua thực hành DevOps (Docker, Flyway, GitHub Actions), kiểm thử nghiêm ngặt (JUnit, Mockito) và phân tích mã nguồn (SonarQube). Có thành tích đã được chứng minh khi làm việc với các phương pháp Agile (Scrum) và đóng góp cho các nhóm phát triển phân tán.' },
  skills: { eyebrow: 'Chuyên môn của tôi', title: 'Kỹ năng Kỹ thuật', categories: [
    { name: 'Ngôn ngữ lập trình', items: ['Java (JDK 8, 11, 14, 17, 21, 22, 25, GraalVM)', 'Scala', 'Python', 'C', 'JavaScript'] },
    { name: 'Framework & Hệ sinh thái Spring', items: ['Spring Boot', 'Spring AOP', 'Spring Cloud', 'Spring Security (JWT)', 'Spring Data JPA', 'Spring Data JDBC', 'Spring Batch', 'Spring MVC', 'Hibernate', 'JPA'] },
    { name: 'Cơ sở dữ liệu', items: ['PostgreSQL', 'PostGIS', 'MySQL', 'SQL Server', 'SQLite', 'H2', 'Oracle DB', 'JDBC', 'Flyway'] },
    { name: 'Kiến trúc Phần mềm', items: ['Microservices', 'Hexagonal Architecture', 'Domain-Driven Design', 'MVC', 'UML 2.0'] },
    { name: 'DevOps & Công cụ', items: ['Docker', 'Maven', 'Gradle', 'Git', 'GitHub Actions', 'Apache Tomcat', 'CI/CD'] },
    { name: 'Kiểm thử & Chất lượng', items: ['JUnit', 'Mockito', 'SonarQube', 'Code Review', 'Clean Code', 'SOLID', 'Design Patterns'] },
    { name: 'Frontend', items: ['HTML5', 'CSS3', 'JavaScript', 'Thymeleaf', 'PrimeFaces', 'Jakarta EE', 'React'] },
    { name: 'Xử lý Dữ liệu', items: ['Apache POI', 'ETL', 'GIS'] }
  ] },
  experience: { eyebrow: 'Sự nghiệp', title: 'Kinh nghiệm Chuyên nghiệp', jobs: [
    { title: 'Chuyên viên Phân tích và Phát triển Java Full-Stack', company: 'Gecytes', period: 'Tháng 11/2024 - Hiện tại', location: 'Từ xa, Mexico', details: ['Thiết kế dịch vụ backend theo Microservices và Kiến trúc Hexagonal.', 'Triển khai RESTful API với Spring Boot và Spring Cloud.', 'Quản lý PostgreSQL (PostGIS) với dữ liệu không gian địa lý.', 'Đảm bảo chất lượng với JUnit, SonarQube và Docker.', 'Cộng tác linh hoạt với Git/GitHub.'], stack: ['Java 17/21/25', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'Hibernate', 'React', 'PostgreSQL (PostGIS)', 'Docker', 'Maven'] },
    { title: 'Lập trình viên Java Backend', company: 'Gestini', period: 'Tháng 5/2025 - Tháng 6/2025', location: 'Từ xa, Argentina', details: ['Thiết kế và triển khai các tính năng backend có khả năng mở rộng.', 'Triển khai kiểm thử đơn vị để đảm bảo độ bền vững và ổn định.'], stack: ['Java 17/21', 'Spring Boot', 'Spring Data', 'Spring Security', 'Hibernate', 'MySQL', 'Docker', 'Maven'] },
    { title: 'Lập trình viên Scala Backend', company: 'Arkon Data', period: 'Tháng 3/2025 - Tháng 5/2025', location: 'Từ xa, Mexico', details: ['Tìm hiểu sâu về Scala và lập trình hàm cho phát triển backend.', 'Phân tích các kiến trúc có khả năng mở rộng và microservices.', 'Tham gia Code Review và tối ưu hóa dịch vụ.'], stack: ['Scala', 'Functional Programming', 'Microservices', 'Git', 'GitHub'] },
    { title: 'Chuyên viên Phân tích và Phát triển Java Back-End', company: 'CUJAE', period: 'Tháng 1/2024 - Tháng 11/2024', location: 'Havana, Cuba', details: ['Lãnh đạo kỹ thuật trong việc chuyển đổi đa nền tảng từ desktop lên web.', 'Tạo RESTful API và tự động hóa ETL với Apache POI.', 'Tối ưu dữ liệu không gian địa lý với PostGIS.'], stack: ['Java 17', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'PostgreSQL (PostGIS)', 'Apache POI', 'Maven'] },
    { title: 'Lập trình viên Java & Chuyên gia Cơ sở dữ liệu', company: 'CUJAE', period: 'Tháng 9/2022 - Tháng 7/2023', location: 'Havana, Cuba', details: ['Phát triển công cụ tự động hóa Java cho di chuyển dữ liệu.', 'Thiết kế lại và tối ưu cơ sở dữ liệu quan hệ.', 'Triển khai trigger và hàm cho tính toàn vẹn tham chiếu.'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'SQL', 'Git', 'GitHub'] },
    { title: 'Chuyên viên Phân tích và Phát triển Phần mềm Java', company: 'CUJAE', period: 'Tháng 1/2022 - Tháng 9/2022', location: 'Havana, Cuba', details: ['Tạo giải pháp quản lý thông tin không gian địa lý.', 'Tự động hóa chuyển đổi Excel sang cơ sở dữ liệu quan hệ.', 'Phát triển giao diện Java Swing cho phân tích dữ liệu.'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'Apache POI', 'GIS', 'Git'] }
  ] },
  projects: { eyebrow: 'Dự án tiêu biểu', title: 'Dự án Nổi bật', list: [
    { title: 'Hệ thống Giám sát & Phân tích Dữ liệu Cảm biến Thông minh', subtitle: 'Luận văn Cử nhân - CUJAE', period: '2024 - 2025', description: 'Hệ thống backend giám sát, quản lý và phân tích dữ liệu từ cảm biến thông minh gắn trên cơ thể. Tích hợp microservices, trí tuệ nhân tạo và IoT để chẩn đoán bệnh lý thông qua phân tích mẫu dáng đi.', highlights: ['Kiến trúc Microservices với Spring Boot và Spring Cloud (Gateway, Eureka)', 'Mạng Nơ-ron với Neuroph để phân loại mẫu dáng đi', 'IoT với cảm biến ESP32 và Bluetooth', 'Ứng dụng Android native đồng bộ SQLite và PostgreSQL', 'Bảo mật với Spring Security (JWT)'], stack: ['Java 17', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'Spring Data JPA', 'Hibernate', 'PostgreSQL', 'SQLite', 'Android', 'Neuroph', 'IoT', 'Maven'] },
    { title: 'Hệ thống Địa lý cho Quản lý Nuôi ong', subtitle: 'Gecytes', period: 'Tháng 11/2024 - Hiện tại', description: 'Hệ thống địa lý cho quản lý nuôi ong tại Mexico với biểu diễn không gian địa lý của tổ ong, trại ong và tuyến đường.', highlights: ['RESTful API mạnh mẽ với tích hợp dữ liệu không gian địa lý', 'Tối ưu hiệu suất và xác thực/phân quyền', 'PostgreSQL với phần mở rộng GIS', 'Quản lý phiên bản cơ sở dữ liệu với Flyway và triển khai Docker', 'Tài liệu kiến trúc toàn diện'], stack: ['Java 17/21/25', 'Spring Boot', 'Spring Cloud', 'Spring Security', 'Spring Data JPA', 'Hibernate', 'PostgreSQL (PostGIS)', 'Flyway', 'Docker', 'Maven', 'JUnit', 'SonarQube'] },
    { title: 'Hệ thống Backend Quản lý Nhân sự với Georeferencing', subtitle: 'CUJAE - Web', period: 'Tháng 1/2024 - Tháng 11/2024', description: 'Hệ thống web quản lý hoạt động của công ty vận tải du lịch với tích hợp không gian địa lý.', highlights: ['Backend với Spring Framework và Spring Data JDBC', 'Giao diện web với JSF và PrimeFaces', 'Mô-đun quản lý tài xế, xe buýt và yêu cầu', 'Sơ đồ kiến trúc và tài liệu kỹ thuật'], stack: ['Java', 'Spring Boot', 'Spring Data JDBC', 'JSF', 'PrimeFaces', 'PostgreSQL', 'Maven', 'Swagger', 'UML'] },
    { title: 'Hệ thống Kiểm soát Tài xế và Xe buýt', subtitle: 'CUJAE - Vận tải Du lịch', period: 'Tháng 9/2023 - Tháng 2/2024', description: 'Hệ thống quản lý cho công ty vận tải du lịch tích hợp backend và frontend web.', highlights: ['Backend với Spring Framework, Spring Data JDBC và Spring MVC', 'Giao diện web với JSF và PrimeFaces', 'Xác thực tính toàn vẹn dữ liệu và quản lý'], stack: ['Java', 'Spring Boot', 'Spring Data JDBC', 'Spring MVC', 'Spring Security', 'JSF', 'PrimeFaces', 'PostgreSQL', 'Maven'] },
    { title: 'Cơ sở dữ liệu Kiểm kê Máy tính', subtitle: 'CUJAE - Khoa Kỹ thuật Máy tính', period: 'Tháng 9/2022 - Tháng 7/2023', description: 'Di chuyển hệ thống kiểm kê dựa trên Excel sang cơ sở dữ liệu quan hệ PostgreSQL.', highlights: ['Di chuyển và chuyển đổi dữ liệu từ Excel sang PostgreSQL', 'Mô hình quản lý kiểm kê có cấu trúc và hiệu quả', 'Truy vấn SQL được tối ưu để trích xuất thông tin'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'Apache POI', 'UML', 'Git'] },
    { title: 'Hệ thống Quản lý Nhân sự với Georeferencing', subtitle: 'CUJAE - Desktop', period: 'Tháng 1/2022 - Tháng 7/2022', description: 'Hệ thống desktop để tập trung dữ liệu Excel vào cơ sở dữ liệu quan hệ với xử lý không gian địa lý.', highlights: ['Nhập và lưu trữ từ Excel sang PostgreSQL', 'Tạo ma trận kết nối hai chiều', 'Tự động hóa với tích hợp GIS'], stack: ['Java', 'Java Swing', 'JDBC', 'PostgreSQL', 'Apache POI', 'GIS', 'UML', 'Git'] },
    { title: 'Hệ thống Kiểm soát Tài xế và Xe buýt', subtitle: 'CUJAE - Desktop', period: 'Tháng 1/2021 - Tháng 11/2021', description: 'Hệ thống desktop quản lý tài xế và xe buýt trong công ty vận tải du lịch.', highlights: ['Logic nghiệp vụ Java hướng đối tượng', 'Giao diện đồ họa với Java Swing', 'Quản lý dữ liệu toàn diện và tài liệu kỹ thuật'], stack: ['Java', 'PostgreSQL', 'Java Swing', 'OOP', 'Eclipse IDE'] }
  ] },
  education: { eyebrow: 'Học vấn', title: 'Học vấn', degree: { title: 'Kỹ thuật Máy tính', institution: 'Đại học Công nghệ Havana "José Antonio Echeverría" (CUJAE)', period: 'Tháng 9/2018 - Hiện tại', detail: 'Dự kiến tốt nghiệp: 2026 (Đang chờ bảo vệ luận văn - Đã hoàn thành tất cả tín chỉ)', focus: 'Đào tạo toàn diện về kỹ thuật phần mềm, thuật toán nâng cao và kiến trúc hệ thống phân tán.' }, complementary: { title: 'Giáo dục Bổ sung', courses: [ { name: 'Học bổng KetherLabs - Datacamp', period: 'Tháng 1/2026 - Hiện tại', detail: 'Xử lý dữ liệu lớn, mô hình hóa thống kê và phân tích dự đoán.' }, { name: 'Chuyên gia Java Backend - Oracle ONE', period: 'Tháng 1/2024 - Tháng 7/2024', detail: 'Hệ sinh thái Java, Spring Framework, Spring Boot, Spring Data JPA/Hibernate, Spring Security, MySQL, SOLID, Clean Code, Design Patterns.' }, { name: 'LinkedIn Learning', period: '', detail: 'Java (Cơ bản đến Nâng cao), Lập trình hàm với Scala, Spring Framework, Spring Data JPA, JDBC, REST APIs, HTML5, CSS3, JavaScript, Git/GitHub, Scrum.' } ] }, languages: { title: 'Ngôn ngữ', items: [ { name: 'Tiếng Tây Ban Nha', level: 'Bản ngữ' }, { name: 'Tiếng Anh', level: 'Trung cấp (A2-B1) | Đọc tài liệu kỹ thuật: Nâng cao' } ] } },
  contact: { eyebrow: 'Kết nối', title: 'Liên hệ', subtitle: 'Tôi luôn sẵn sàng cho cơ hội việc làm và hợp tác.', email: 'raynersoto01@gmail.com', phone: '+1 (863) 766-8212', whatsapp: '+1 (863) 397-6979', location: 'Havana, Cuba', linkedin: 'linkedin.com/in/rayner-alejandro', github: 'github.com/RaynerSoto' },
  footer: { copyright: '\u00a9 2026 Rayner Alejandro Soto Mart\u00ednez. Đã đăng ký bản quyền.', built: 'Được xây dựng bằng' }
};
